Página inicial Dojo de Python
SuPyPerson/Intro_Python pull request #2
Opened 2022-10-25 11:08 UTC by ericascheffel

2022-10-25 12:34 UTC, cetoli commented
Rejeitado porque inclui arquivos de configuração do Pycharm

2022-10-25 13:07 UTC, cetoli commented on docs/source/Dojo_de_Python.html
> +<?xml version="1.0" encoding="utf-8" ?>
Não deve ter html no commit

2022-10-25 13:10 UTC, cetoli commented on docs/source/Dojo_de_Python.rst
> +.. _modulo_inicia:
Porque este arquivo marcado como rst está cheio de html?

2022-10-25 13:24 UTC, cetoli requested changes
Existem problemas neste texto, os comentários estão assinalados

2022-10-25 13:24 UTC, cetoli commented on docs/source/Dojo_de_Python_main.rst
> +.. _ppfc:
esta âncora já existe na documentação original : [Intro_Python](https://github.com/SuPyPerson/Intro_Python)/[docs](https://github.com/SuPyPerson/Intro_Python/tree/main/docs)/[source](https://github.com/SuPyPerson/Intro_Python/tree/main/docs/source)/index.rst Troque para outro identificador como: .. _dojo_main:

2022-10-25 13:24 UTC, cetoli commented on docs/source/Dojo_de_Python_main.rst
> +====================================================
A sequência de ==== deve continuar até sublinhar toda o título.

2022-10-25 13:24 UTC, cetoli commented on docs/source/Dojo_de_Python_main.rst
> +    index.rst
Aqui deveria ser o nome do primeiro arquivo de problema: problema_1.rst

2022-10-25 13:24 UTC, cetoli commented on docs/source/inicia.rst
> +pip.. _modulo_inicia:
acho que este pip aqui entrou por engano

2022-10-25 13:32 UTC, cetoli requested changes
você deve adicionar .idea no .gitignore para que os arquivos de configuração do pycharm não subam para o repositório. o destino do html gerado deve ser o diretório build. se você observar o ignore da raiz ele já exclui o build [https://github.com/SuPyPerson/Intro_Python/blob/main/.gitignore](url). Estude mais um pouco ReStructuredText para melhorar sua página.

2022-10-25 18:57 UTC, ericascheffel commented on docs/source/Dojo_de_Python.html
> +<?xml version="1.0" encoding="utf-8" ?>
Corrigido.

2022-10-25 18:57 UTC, ericascheffel commented on docs/source/Dojo_de_Python.rst
> +.. _modulo_inicia:
Esse arquivo foi excluído.

2022-10-25 18:57 UTC, ericascheffel commented on docs/source/Dojo_de_Python_main.rst
> +====================================================
Corrigido.

2022-10-25 18:57 UTC, ericascheffel commented on docs/source/inicia.rst
> +pip.. _modulo_inicia:
Corrigido.

2022-10-25 18:59 UTC, ericascheffel commented on docs/source/Dojo_de_Python_main.rst
> +    index.rst
Coloquei como exemplo, os alunos que deverão criar a página dos desafios e alterar o nome (link).

2022-10-25 21:59 UTC, ericascheffel commented on docs/source/Dojo_de_Python_main.rst
> +.. _ppfc:
Corrigido.

2022-10-26 00:16 UTC, ericascheffel reviewed
Correção dos arquivos e melhoria da página inicial.

2022-10-26 00:18 UTC, closed without merging